---
abstract: 'Validate Indonesian citizenship registration number (NIK)'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102343, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-ID-NIK
requires:
  DateTime: 0
  perl: 5.010000
resources:
  homepage: http://search.cpan.org/dist/Business-ID-NIK/
  repository: http://github.com/sharyanto/perl-Business-ID-NIK
version: 0.03
